Update gradle.yml

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -1,92 +1,49 @@
-name: Java CI with Gradle
+name: CICD Test
 
 on:
-  push:
-    branches: [ "main", "develop" ]
+  pull_request:
+    branches:
+      - develop
 
-permissions:
-  checks: write
-  pull-requests: write
+env:
+  AWS_REGION: ap-northeast-2
+  AWS_S3_BUCKET: app-release-files
+  AWS_CODE_DEPLOY_APPLICATION: cicid-test-CD
+  AWS_CODE_DEPLOY_GROUP: cicd-test-CD-group
 
 jobs:
-  test:
-
-    runs-on: ubuntu-latest
-
+  build-with-gradle:
+    runs-on: ubuntu-20.04
     steps:
-    - uses: actions/checkout@v3
-    - name: Set up JDK 17
+    - name: Checkout Code
+      uses: actions/checkout@v3
+      with:
+        ref: ${{ github.event.before }}
+    - name: Checkout PR Code
+      uses: actions/checkout@v3
+    - name: JDK 17 Installation
       uses: actions/setup-java@v3
       with:
         java-version: '17'
-        distribution: 'adopt'
-
-    
-    # 환경별 yml 파일 생성(1) - application.yml
-    - name: make application.yml
-      shell: bash
+        distribution: 'corretto'
+    - name: Grant execute permission to gradlew
+      run: chmod +x ./gradlew
+    - name: Build Project
+      run: ./gradlew clean build -x test
+    - name: Check Test Status
       run: |
-          touch ./src/main/resources/application.yml 
-          echo "${{ secrets.YML }}" > ./application.yml  # github actions에서 설정한 값을 application.yml 파일에 쓰기
-      
-
-
-    - name: make jwt.yml
-      shell: bash
-      run: |
-          touch src/main/resources/jwt.yml 
-          echo "${{ secrets.JWT_YML }}" > src/main/resources/jwt.yml  # github actions에서 설정한 값을 application.yml 파일에 쓰기
-      
-      
-    # gradle caching - 빌드 시간 향상
-    - name: Gradle Caching
-      uses: actions/cache@v3
+        test_status=$(./gradlew test --rerun-tasks --quiet)
+        if [ "$test_status" != "BUILD SUCCESSFUL" ]; then
+          echo "Tests failed. Aborting deployment."
+          exit 1
+        fi
+    - name: Configure AWS Credentials
+      uses: aws-actions/configure-aws-credentials@v1
       with:
-        path: |
-          ~/.gradle/caches
-          ~/.gradle/wrapper
-        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
-        restore-keys: |
-          ${{ runner.os }}-gradle-
-          
-    # Gradle wrapper 파일 실행 권한주기
-    - name: Grant execute permission for gradlew
-      run: chmod +x gradlew
-        
-    # Gradle test를 실행한다
-    - name: Test with Gradle
-      run: ./gradlew --info test
-
-    # 테스트 후 Result를 보기위해 Publish Unit Test Results step 추가
-    - name: 테스트 결과 Report
-      uses: EnricoMi/publish-unit-test-result-action@v2
-      if: always()  # 테스트가 실패하여도 Report를 보기 위해 `always`로 설정
-      with:
-         files: 'build/test-results/**/*.xml'
-    
-    - name: 테스트 실패 Comment
-      uses: mikepenz/action-junit-report@v3
-      if: always()
-      with:
-        report_paths: 'build/test-results/test/TEST-*.xml'
-
-
-        
-    # 추가
-    - name: Cleanup Gradle Cache
-      # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
-      # Restoring these files from a GitHub Actions cache might cause problems for future builds.
-      if: ${{ always() }}
-      run: |
-        rm -f ~/.gradle/caches/modules-2/modules-2.lock
-        rm -f ~/.gradle/caches/modules-2/gc.properties
-
-
-      
-    # 빌드
-    - name: Build with Gradle
-      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
-      with:
-        arguments: build
-
-    
+        aws-region: ${{ env.AWS_REGION }}
+        aws-access-key-id: ${{ secrets.CICD_ACCESS_KEY }}
+        aws-secret-access-key: ${{ secrets.CICD_SECRET_KEY }}
+    - name: Upload to S3
+      run: aws deploy push --application-name ${{ env.AWS_CODE_DEPLOY_APPLICATION }} --ignore-hidden-files --s3-location s3://$AWS_S3_BUCKET/cicdtest/$GITHUB_SHA.zip --source .
+    - name: Deploy to EC2 using AWS CodeDeploy
+      run: aws deploy create-deployment --application-name ${{ env.AWS_CODE_DEPLOY_APPLICATION }} --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name ${{ env.AWS_CODE_DEPLOY_GROUP }} --s3-location bucket=$AWS_S3_BUCKET,key=cicdtest/$GITHUB_SHA.zip,bundleType=zip
